<a href="https://colab.research.google.com/github/psilva0/An-lise-de-atrasos-de-pedidos/blob/main/Projeto_Avalia%C3%A7%C3%B5es.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Instala a biblioteca (rode isso em uma célula separada no topo do Colab)
!pip install kagglehub[pandas-datasets]

import kagglehub
from kagglehub import KaggleDatasetAdapter

# 1. Carregando a tabela de Pedidos (Orders)
df_pedidos = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "olistbr/brazilian-ecommerce",
  "olist_orders_dataset.csv" # Nome exato do arquivo no Kaggle
)

# 2. Carregando a tabela de Avaliações (Reviews)
df_avaliacoes = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "olistbr/brazilian-ecommerce",
  "olist_order_reviews_dataset.csv" # Nome exato do arquivo no Kaggle
)

print("Estrutura de Pedidos:")
display(df_pedidos.head())

print("\nEstrutura de Avaliações:")
display(df_avaliacoes.head())

Requirement already satisfied: kagglehub[pandas-datasets] in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.2.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.14->kagglehub[pandas-datasets]) (5.29.6)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)

/tmp/ipykernel_159/3719960529.py:8: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_pedidos = kagglehub.load_dataset(

Using Colab cache for faster access to the 'brazilian-ecommerce' dataset.

/tmp/ipykernel_159/3719960529.py:15: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_avaliacoes = kagglehub.load_dataset(

Using Colab cache for faster access to the 'brazilian-ecommerce' dataset.
Estrutura de Pedidos:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

Estrutura de Avaliações:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [ ]:
df_avaliacoes.shape

(99224, 7)

In [ ]:
df_pedidos.shape

(99441, 8)

--

In [ ]:
import pandas as pd

In [ ]:
df = pd.merge(df_avaliacoes, df_pedidos, on='order_id', how='left')

In [ ]:
df.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59,41dcb106f807e993532d446263290104,delivered,2018-01-11 15:30:49,2018-01-11 15:47:59,2018-01-12 21:57:22,2018-01-17 18:42:41,2018-02-02 00:00:00
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13,8a2e7ef9053dea531e4dc76bd6d853e6,delivered,2018-02-28 12:25:19,2018-02-28 12:48:39,2018-03-02 19:08:15,2018-03-09 23:17:20,2018-03-14 00:00:00
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24,e226dfed6544df5b7b87a48208690feb,delivered,2018-02-03 09:56:22,2018-02-03 10:33:41,2018-02-06 16:18:28,2018-02-16 17:28:48,2018-03-09 00:00:00
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,de6dff97e5f1ba84a3cd9a3bc97df5f6,delivered,2017-04-09 17:41:13,2017-04-09 17:55:19,2017-04-10 14:24:47,2017-04-20 09:08:35,2017-05-10 00:00:00
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53,5986b333ca0d44534a156a52a8e33a83,delivered,2018-02-10 10:59:03,2018-02-10 15:48:21,2018-02-15 19:36:14,2018-02-28 16:33:35,2018-03-09 00:00:00

In [ ]:
df.shape

(99224, 14)

In [ ]:
df.dtypes

review_id                        object
order_id                         object
review_score                      int64
review_comment_title             object
review_comment_message           object
review_creation_date             object
review_answer_timestamp          object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [ ]:
df = df.drop(columns=['review_id', 'review_comment_title', 'review_creation_date', 'review_answer_timestamp', 'order_approved_at', 'order_delivered_carrier_date'], errors='ignore')
display(df.head())

,order_id,review_score,review_comment_message,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date
0,73fc7af87114b39712e6da79b0a377eb,4,NaN,41dcb106f807e993532d446263290104,delivered,2018-01-11 15:30:49,2018-01-17 18:42:41,2018-02-02 00:00:00
1,a548910a1c6147796b98fdf73dbeba33,5,NaN,8a2e7ef9053dea531e4dc76bd6d853e6,delivered,2018-02-28 12:25:19,2018-03-09 23:17:20,2018-03-14 00:00:00
2,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,e226dfed6544df5b7b87a48208690feb,delivered,2018-02-03 09:56:22,2018-02-16 17:28:48,2018-03-09 00:00:00
3,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,de6dff97e5f1ba84a3cd9a3bc97df5f6,delivered,2017-04-09 17:41:13,2017-04-20 09:08:35,2017-05-10 00:00:00
4,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,5986b333ca0d44534a156a52a8e33a83,delivered,2018-02-10 10:59:03,2018-02-28 16:33:35,2018-03-09 00:00:00

In [ ]:
df.head()

,order_id,review_score,review_comment_message,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date
0,73fc7af87114b39712e6da79b0a377eb,4,NaN,41dcb106f807e993532d446263290104,delivered,2018-01-11 15:30:49,2018-01-17 18:42:41,2018-02-02 00:00:00
1,a548910a1c6147796b98fdf73dbeba33,5,NaN,8a2e7ef9053dea531e4dc76bd6d853e6,delivered,2018-02-28 12:25:19,2018-03-09 23:17:20,2018-03-14 00:00:00
2,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,e226dfed6544df5b7b87a48208690feb,delivered,2018-02-03 09:56:22,2018-02-16 17:28:48,2018-03-09 00:00:00
3,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,de6dff97e5f1ba84a3cd9a3bc97df5f6,delivered,2017-04-09 17:41:13,2017-04-20 09:08:35,2017-05-10 00:00:00
4,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,5986b333ca0d44534a156a52a8e33a83,delivered,2018-02-10 10:59:03,2018-02-28 16:33:35,2018-03-09 00:00:00

In [ ]:
df.isnull().sum()

order_id                             0
review_score                         0
review_comment_message           58247
customer_id                          0
order_status                         0
order_purchase_timestamp             0
order_delivered_customer_date     2865
order_estimated_delivery_date        0
dtype: int64

--

In [ ]:
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
px.box(df['review_score'])

In [ ]:
df[['review_score', 'review_comment_message']]

       review_score                             review_comment_message
0                 4                                                NaN
1                 5                                                NaN
2                 5                                                NaN
3                 5              Recebi bem antes do prazo estipulado.
4                 5  Parabéns lojas lannister adorei comprar pela I...
...             ...                                                ...
99219             5                                                NaN
99220             5                                                NaN
99221             5  Excelente mochila, entrega super rápida. Super...
99222             4                                                NaN
99223             1  meu produto chegou e ja tenho que devolver, po...

[99224 rows x 2 columns]

Df + coluna dias ( do momento da compra ate chegar) e previsão do tempo da compra até chegar.

In [ ]:
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'])
df['order_estimated_delivery_date'] = pd.to_datetime(df['order_estimated_delivery_date'])

df['dias_para_chegar'] = (df['order_delivered_customer_date'] - df['order_purchase_timestamp']).dt.days
df['dias_para_chegar_estimado'] = (df['order_estimated_delivery_date'] - df['order_purchase_timestamp']).dt.days

display(df[['order_purchase_timestamp', 'order_delivered_customer_date', 'dias_para_chegar', 'order_estimated_delivery_date', 'dias_para_chegar_estimado']].head())
display(df['dias_para_chegar'].isnull().sum())
display(df['dias_para_chegar'].dtype)
display(df['dias_para_chegar_estimado'].isnull().sum())
display(df['dias_para_chegar_estimado'].dtype)

,order_purchase_timestamp,order_delivered_customer_date,dias_para_chegar,order_estimated_delivery_date,dias_para_chegar_estimado
0,2018-01-11 15:30:49,2018-01-17 18:42:41,6.0,2018-02-02,21
1,2018-02-28 12:25:19,2018-03-09 23:17:20,9.0,2018-03-14,13
2,2018-02-03 09:56:22,2018-02-16 17:28:48,13.0,2018-03-09,33
3,2017-04-09 17:41:13,2017-04-20 09:08:35,10.0,2017-05-10,30
4,2018-02-10 10:59:03,2018-02-28 16:33:35,18.0,2018-03-09,26

np.int64(2865)

dtype('float64')

np.int64(0)

dtype('int64')

In [ ]:
df2 = df.drop(columns=['order_purchase_timestamp','order_delivered_customer_date', 'order_estimated_delivery_date'], errors='ignore')
display(df.head())

,order_id,review_score,review_comment_message,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,dias_para_chegar,dias_para_chegar_estimado
0,73fc7af87114b39712e6da79b0a377eb,4,NaN,41dcb106f807e993532d446263290104,delivered,2018-01-11 15:30:49,2018-01-17 18:42:41,2018-02-02,6.0,21
1,a548910a1c6147796b98fdf73dbeba33,5,NaN,8a2e7ef9053dea531e4dc76bd6d853e6,delivered,2018-02-28 12:25:19,2018-03-09 23:17:20,2018-03-14,9.0,13
2,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,e226dfed6544df5b7b87a48208690feb,delivered,2018-02-03 09:56:22,2018-02-16 17:28:48,2018-03-09,13.0,33
3,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,de6dff97e5f1ba84a3cd9a3bc97df5f6,delivered,2017-04-09 17:41:13,2017-04-20 09:08:35,2017-05-10,10.0,30
4,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,5986b333ca0d44534a156a52a8e33a83,delivered,2018-02-10 10:59:03,2018-02-28 16:33:35,2018-03-09,18.0,26

In [ ]:
df2 = df2.dropna(subset=['dias_para_chegar', 'dias_para_chegar_estimado'])

In [ ]:
df2.head()

,order_id,review_score,review_comment_message,customer_id,order_status,dias_para_chegar,dias_para_chegar_estimado
0,73fc7af87114b39712e6da79b0a377eb,4,NaN,41dcb106f807e993532d446263290104,delivered,6.0,21
1,a548910a1c6147796b98fdf73dbeba33,5,NaN,8a2e7ef9053dea531e4dc76bd6d853e6,delivered,9.0,13
2,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,e226dfed6544df5b7b87a48208690feb,delivered,13.0,33
3,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,de6dff97e5f1ba84a3cd9a3bc97df5f6,delivered,10.0,30
4,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,5986b333ca0d44534a156a52a8e33a83,delivered,18.0,26

In [ ]:
df2['houve_atraso'] = (df2['dias_para_chegar'] > df2['dias_para_chegar_estimado'])
display(df2.head())

,order_id,review_score,review_comment_message,customer_id,order_status,dias_para_chegar,dias_para_chegar_estimado,houve_atraso
0,73fc7af87114b39712e6da79b0a377eb,4,NaN,41dcb106f807e993532d446263290104,delivered,6.0,21,False
1,a548910a1c6147796b98fdf73dbeba33,5,NaN,8a2e7ef9053dea531e4dc76bd6d853e6,delivered,9.0,13,False
2,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,e226dfed6544df5b7b87a48208690feb,delivered,13.0,33,False
3,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,de6dff97e5f1ba84a3cd9a3bc97df5f6,delivered,10.0,30,False
4,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,5986b333ca0d44534a156a52a8e33a83,delivered,18.0,26,False

--

In [ ]:
df2.groupby('houve_atraso')['review_score'].mean()

houve_atraso
False    4.292077
True     2.460885
Name: review_score, dtype: float64

de onde são os atrasos?

In [ ]:
# 1. Carregando a tabela de Clientes do Kaggle
df_clientes = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "olistbr/brazilian-ecommerce",
  "olist_customers_dataset.csv"
)


df_completo = pd.merge(df2, df_clientes[['customer_id', 'customer_state']], on='customer_id', how='left')

/tmp/ipykernel_159/2080859425.py:2: DeprecationWarning:

Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.

Using Colab cache for faster access to the 'brazilian-ecommerce' dataset.

In [ ]:
df_completo.groupby('customer_state')['houve_atraso'].sum().sort_values(ascending=False)

customer_state
SP    2125
RJ    1563
MG     582
BA     422
RS     352
SC     320
ES     227
PR     223
CE     189
PE     160
GO     144
DF     139
MA     132
PA     109
AL      89
MS      77
PI      71
MT      54
PB      53
SE      50
RN      47
TO      34
RO       7
AM       5
RR       5
AC       3
AP       2
Name: houve_atraso, dtype: int64

In [ ]:
taxa_atraso_uf = df_completo.groupby('customer_state')['houve_atraso'].mean().sort_values(ascending=False) * 100

print("Taxa de atraso por Estado (%):")
print(taxa_atraso_uf.head())

Taxa de atraso por Estado (%):
customer_state
AL    22.361809
MA    18.435754
PI    15.042373
SE    14.970060
CE    14.811912
Name: houve_atraso, dtype: float64

In [ ]:
df_completo.shape

(96359, 9)

In [ ]:
df_completo.head()

,order_id,review_score,review_comment_message,customer_id,order_status,dias_para_chegar,dias_para_chegar_estimado,houve_atraso,customer_state
0,73fc7af87114b39712e6da79b0a377eb,4,NaN,41dcb106f807e993532d446263290104,delivered,6.0,21,False,SP
1,a548910a1c6147796b98fdf73dbeba33,5,NaN,8a2e7ef9053dea531e4dc76bd6d853e6,delivered,9.0,13,False,SP
2,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,e226dfed6544df5b7b87a48208690feb,delivered,13.0,33,False,BA
3,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,de6dff97e5f1ba84a3cd9a3bc97df5f6,delivered,10.0,30,False,SC
4,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,5986b333ca0d44534a156a52a8e33a83,delivered,18.0,26,False,SC

In [ ]:
# Exportando a base final tratada
df_completo.to_csv('base_logistica_final.csv', index=False)